In [2]:
import pandas as pd
import numpy as np

In [3]:
columns=["user_id","order_dt","order_products","order_amount"]

In [104]:
df=pd.read_table("CDNOW_master.txt",names=columns,sep="\s+")

In [62]:
df.head()

KeyError: 'name'

In [105]:
df["order_dt"]=pd.to_datetime(df.order_dt,format="%Y%m%d")

In [106]:
df["month"]=df.order_dt.values.astype("datetime64[M]")

In [8]:
df.groupby("user_id").min().order_dt.value_counts()

1997-02-08    363
1997-02-24    347
1997-02-04    346
1997-02-06    346
1997-03-04    340
1997-02-27    339
1997-03-06    337
1997-02-03    335
1997-02-17    332
1997-02-25    328
1997-03-05    325
1997-01-29    322
1997-03-12    321
1997-03-02    317
1997-02-09    316
1997-02-26    315
1997-02-18    315
1997-03-10    314
1997-01-19    314
1997-01-27    308
1997-03-07    306
1997-02-01    305
1997-01-26    305
1997-03-01    300
1997-03-03    300
1997-02-10    300
1997-03-09    299
1997-03-16    299
1997-01-24    299
1997-02-11    296
             ...
1997-03-20    271
1997-01-31    267
1997-01-12    266
1997-03-24    263
1997-01-23    262
1997-02-22    262
1997-01-06    261
1997-01-25    256
1997-02-21    254
1997-03-15    253
1997-03-22    250
1997-01-05    250
1997-01-21    248
1997-02-14    244
1997-01-02    241
1997-03-25    241
1997-01-17    236
1997-01-16    234
1997-01-13    232
1997-01-03    228
1997-01-22    220
1997-01-14    220
1997-01-09    219
1997-01-15    219
1997-01-10    217
1997-01-08    213
1997-03-21    213
1997-01-07    211
1997-01-01    209
1997-01-04    174
Name: order_dt, Length: 84, dtype: int64

In [9]:
user_life=df.groupby("user_id").order_dt.agg(["min","max"])

In [10]:
(user_life["min"]==user_life["max"]).value_counts()

True     12054
False    11516
dtype: int64

In [11]:
user_life

               min        max
user_id
1       1997-01-01 1997-01-01
2       1997-01-12 1997-01-12
3       1997-01-02 1998-05-28
4       1997-01-01 1997-12-12
5       1997-01-01 1998-01-03
6       1997-01-01 1997-01-01
7       1997-01-01 1998-03-22
8       1997-01-01 1998-03-29
9       1997-01-01 1998-06-08
10      1997-01-21 1997-01-21
11      1997-01-01 1998-02-20
12      1997-01-01 1997-01-01
13      1997-01-01 1997-01-01
14      1997-01-01 1997-01-01
15      1997-01-01 1997-01-01
16      1997-01-01 1997-09-10
17      1997-01-01 1997-01-01
18      1997-01-04 1997-01-04
19      1997-01-01 1997-06-10
20      1997-01-01 1997-01-18
21      1997-01-01 1997-01-13
22      1997-01-01 1997-01-01
23      1997-01-01 1997-01-01
24      1997-01-01 1998-01-20
25      1997-01-01 1998-06-08
26      1997-01-01 1997-01-26
27      1997-01-07 1997-01-12
28      1997-01-01 1997-03-08
29      1997-01-01 1998-04-26
30      1997-01-01 1997-02-14
...            ...        ...
23541   1997-03-25 1997-04-02
23542   1997-03-25 1997-03-25
23543   1997-03-25 1997-03-25
23544   1997-03-25 1998-01-24
23545   1997-03-25 1997-03-25
23546   1997-03-25 1997-03-25
23547   1997-03-25 1997-04-07
23548   1997-03-25 1997-03-25
23549   1997-03-25 1997-03-25
23550   1997-03-25 1997-03-25
23551   1997-03-25 1997-09-11
23552   1997-03-25 1997-04-03
23553   1997-03-25 1997-03-28
23554   1997-03-25 1998-02-01
23555   1997-03-25 1998-06-10
23556   1997-03-25 1998-06-07
23557   1997-03-25 1997-03-25
23558   1997-03-25 1998-02-25
23559   1997-03-25 1997-06-27
23560   1997-03-25 1997-03-25
23561   1997-03-25 1998-05-29
23562   1997-03-25 1997-03-25
23563   1997-03-25 1997-10-04
23564   1997-03-25 1997-11-30
23565   1997-03-25 1997-03-25
23566   1997-03-25 1997-03-25
23567   1997-03-25 1997-03-25
23568   1997-03-25 1997-04-22
23569   1997-03-25 1997-03-25
23570   1997-03-25 1997-03-26

[23570 rows x 2 columns]

In [12]:
a=df.groupby("user_id").count()

In [13]:
(a["order_dt"]==1).value_counts()

True     11908
False    11662
Name: order_dt, dtype: int64

In [14]:
a

         order_dt  order_products  order_amount  month
user_id
1               1               1             1      1
2               2               2             2      2
3               6               6             6      6
4               4               4             4      4
5              11              11            11     11
6               1               1             1      1
7               3               3             3      3
8               8               8             8      8
9               3               3             3      3
10              1               1             1      1
11              4               4             4      4
12              1               1             1      1
13              1               1             1      1
14              1               1             1      1
15              1               1             1      1
16              4               4             4      4
17              1               1             1      1
18              1               1             1      1
19              2               2             2      2
20              2               2             2      2
21              2               2             2      2
22              1               1             1      1
23              1               1             1      1
24              2               2             2      2
25              8               8             8      8
26              2               2             2      2
27              2               2             2      2
28              3               3             3      3
29             12              12            12     12
30              2               2             2      2
...           ...             ...           ...    ...
23541           2               2             2      2
23542           1               1             1      1
23543           1               1             1      1
23544           3               3             3      3
23545           1               1             1      1
23546           1               1             1      1
23547           2               2             2      2
23548           1               1             1      1
23549           1               1             1      1
23550           1               1             1      1
23551           6               6             6      6
23552           2               2             2      2
23553           2               2             2      2
23554           2               2             2      2
23555           5               5             5      5
23556           7               7             7      7
23557           1               1             1      1
23558           4               4             4      4
23559           3               3             3      3
23560           1               1             1      1
23561           3               3             3      3
23562           1               1             1      1
23563           2               2             2      2
23564           3               3             3      3
23565           1               1             1      1
23566           1               1             1      1
23567           1               1             1      1
23568           3               3             3      3
23569           1               1             1      1
23570           2               2             2      2

[23570 rows x 4 columns]

In [15]:
rfm=df.pivot_table(index="user_id",
                  values=["order_dt","order_amount","order_products"],
                  aggfunc={"order_dt":"max",
                           "order_amount":"sum", 
                           "order_products":"sum"})

In [16]:
rfm.head()

         order_amount   order_dt  order_products
user_id
1               11.77 1997-01-01               1
2               89.00 1997-01-12               6
3              156.46 1998-05-28              16
4              100.50 1997-12-12               7
5              385.61 1998-01-03              29

In [17]:
a=rfm[["R","F","M"]].apply(lambda x:x-x.mean())
a

KeyError: "['R' 'F' 'M'] not in index"

In [18]:
rfm.rename(columns={"order_products":"F","order_amount":"M"},inplace=True)

In [19]:
a=rfm[["R","F","M"]].apply(lambda x:x-x.mean())
a

KeyError: "['R'] not in index"

In [20]:
def rfm_func(x):
    level=x.apply(lambda x:"1" if x>=0 else "0")
    label=level.R+level.F+level.M
    d={"111":"hu",
       "110":"jih",
       "101":"hius",
       "100":"gdu",
       "001":"hdsf",
       "000":"ers",
       "010":"ersf",
       "011":"ytuvshg"   
    }
    result=d[label]
    return result

In [21]:
rfm["label"]=a.apply(rfm_func,axis=1)

AttributeError: ("'Series' object has no attribute 'R'", 'occurred at index 1')

In [22]:
rfm

              M   order_dt   F
user_id
1         11.77 1997-01-01   1
2         89.00 1997-01-12   6
3        156.46 1998-05-28  16
4        100.50 1997-12-12   7
5        385.61 1998-01-03  29
6         20.99 1997-01-01   1
7        264.67 1998-03-22  18
8        197.66 1998-03-29  18
9         95.85 1998-06-08   6
10        39.31 1997-01-21   3
11        58.55 1998-02-20   4
12        57.06 1997-01-01   4
13        72.94 1997-01-01   4
14        29.92 1997-01-01   2
15        52.87 1997-01-01   4
16        79.87 1997-09-10   8
17        73.22 1997-01-01   5
18        14.96 1997-01-04   1
19       175.12 1997-06-10  11
20       653.01 1997-01-18  46
21        75.11 1997-01-13   4
22        14.37 1997-01-01   1
23        24.74 1997-01-01   2
24        57.77 1998-01-20   4
25       137.53 1998-06-08  12
26       102.69 1997-01-26   6
27       135.87 1997-01-12  10
28        90.99 1997-03-08   7
29       435.81 1998-04-26  28
30        28.34 1997-02-14   2
...         ...        ...  ..
23541     57.34 1997-04-02   2
23542     77.43 1997-03-25   5
23543     50.76 1997-03-25   2
23544    134.63 1998-01-24  12
23545     24.99 1997-03-25   1
23546     13.97 1997-03-25   1
23547     23.54 1997-04-07   2
23548     23.54 1997-03-25   2
23549     27.13 1997-03-25   2
23550     25.28 1997-03-25   2
23551    264.63 1997-09-11  12
23552     49.38 1997-04-03   4
23553     98.58 1997-03-28   8
23554     36.37 1998-02-01   3
23555    189.18 1998-06-10  14
23556    203.00 1998-06-07  15
23557     14.37 1997-03-25   1
23558    145.60 1998-02-25  11
23559    111.65 1997-06-27   8
23560     18.36 1997-03-25   1
23561     83.46 1998-05-29   6
23562     29.33 1997-03-25   2
23563     58.75 1997-10-04   3
23564     70.01 1997-11-30   5
23565     11.77 1997-03-25   1
23566     36.00 1997-03-25   2
23567     20.97 1997-03-25   1
23568    121.70 1997-04-22   6
23569     25.74 1997-03-25   2
23570     94.08 1997-03-26   5

[23570 rows x 3 columns]

In [23]:
df

       user_id   order_dt  order_products  order_amount      month
0            1 1997-01-01               1         11.77 1997-01-01
1            2 1997-01-12               1         12.00 1997-01-01
2            2 1997-01-12               5         77.00 1997-01-01
3            3 1997-01-02               2         20.76 1997-01-01
4            3 1997-03-30               2         20.76 1997-03-01
5            3 1997-04-02               2         19.54 1997-04-01
6            3 1997-11-15               5         57.45 1997-11-01
7            3 1997-11-25               4         20.96 1997-11-01
8            3 1998-05-28               1         16.99 1998-05-01
9            4 1997-01-01               2         29.33 1997-01-01
10           4 1997-01-18               2         29.73 1997-01-01
11           4 1997-08-02               1         14.96 1997-08-01
12           4 1997-12-12               2         26.48 1997-12-01
13           5 1997-01-01               2         29.33 1997-01-01
14           5 1997-01-14               1         13.97 1997-01-01
15           5 1997-02-04               3         38.90 1997-02-01
16           5 1997-04-11               3         45.55 1997-04-01
17           5 1997-05-31               3         38.71 1997-05-01
18           5 1997-06-16               2         26.14 1997-06-01
19           5 1997-07-22               2         28.14 1997-07-01
20           5 1997-09-15               3         40.47 1997-09-01
21           5 1997-12-08               4         46.46 1997-12-01
22           5 1997-12-12               3         40.47 1997-12-01
23           5 1998-01-03               3         37.47 1998-01-01
24           6 1997-01-01               1         20.99 1997-01-01
25           7 1997-01-01               2         28.74 1997-01-01
26           7 1997-10-11               7         97.43 1997-10-01
27           7 1998-03-22               9        138.50 1998-03-01
28           8 1997-01-01               1          9.77 1997-01-01
29           8 1997-02-13               1         13.97 1997-02-01
...        ...        ...             ...           ...        ...
69629    23556 1997-09-27               3         31.47 1997-09-01
69630    23556 1998-01-03               2         28.98 1998-01-01
69631    23556 1998-06-07               2         28.98 1998-06-01
69632    23557 1997-03-25               1         14.37 1997-03-01
69633    23558 1997-03-25               2         28.13 1997-03-01
69634    23558 1997-05-18               3         45.51 1997-05-01
69635    23558 1997-06-24               2         23.74 1997-06-01
69636    23558 1998-02-25               4         48.22 1998-02-01
69637    23559 1997-03-25               2         23.54 1997-03-01
69638    23559 1997-05-18               3         35.31 1997-05-01
69639    23559 1997-06-27               3         52.80 1997-06-01
69640    23560 1997-03-25               1         18.36 1997-03-01
69641    23561 1997-03-25               2         30.92 1997-03-01
69642    23561 1998-01-28               1         15.49 1998-01-01
69643    23561 1998-05-29               3         37.05 1998-05-01
69644    23562 1997-03-25               2         29.33 1997-03-01
69645    23563 1997-03-25               1         10.77 1997-03-01
69646    23563 1997-10-04               2         47.98 1997-10-01
69647    23564 1997-03-25               1         11.77 1997-03-01
69648    23564 1997-05-21               1         11.77 1997-05-01
69649    23564 1997-11-30               3         46.47 1997-11-01
69650    23565 1997-03-25               1         11.77 1997-03-01
69651    23566 1997-03-25               2         36.00 1997-03-01
69652    23567 1997-03-25               1         20.97 1997-03-01
69653    23568 1997-03-25               1         22.97 1997-03-01
69654    23568 1997-04-05               4         83.74 1997-04-01
69655    23568 1997-04-22               1         14.99 1997-04-01
69656    23569 1997-03-25               2         25.74 1997-03-01
69657    23570 1997-03-25               3         51.12 1997-03-01
69658    23570 1997-03-26               2         42.96 1997-03-01

[69659 rows x 5 columns]

In [28]:
pivoted_counts=df.pivot_table(index="user_id",columns="month",values="order_amount",aggfunc="count").fillna(0)

In [76]:
pivoted_counts

month,1997-01-01 00:00:00,1997-02-01 00:00:00,1997-03-01 00:00:00,1997-04-01 00:00:00,1997-05-01 00:00:00,1997-06-01 00:00:00,1997-07-01 00:00:00,1997-08-01 00:00:00,1997-09-01 00:00:00,1997-10-01 00:00:00,1997-11-01 00:00:00,1997-12-01 00:00:00,1998-01-01 00:00:00,1998-02-01 00:00:00,1998-03-01 00:00:00,1998-04-01 00:00:00,1998-05-01 00:00:00,1998-06-01 00:00:00
user_id,,,,,,,,,,,,,,,,,,
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0
6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
8,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
9,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
12,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
25,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
26,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,1.0,1.0,1.0,2.0,2.0,0.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
30,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23541,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23542,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23543,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23544,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
23545,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23546,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23547,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23548,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23549,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23550,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23551,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23552,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23553,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23554,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
23555,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
23556,0.0,0.0,1.0,0.0,0.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
23557,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23558,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
23559,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23560,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23561,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
23562,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23563,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23564,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23565,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23566,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23567,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23568,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23569,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23570,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [88]:
df_purchase=pivoted_counts.applymap(lambda x:1 if x>0 else 0)

In [89]:
df_purchase
df_purchase.apply(lambda x:x-x.mean(),axis=1)

month,1997-01-01 00:00:00,1997-02-01 00:00:00,1997-03-01 00:00:00,1997-04-01 00:00:00,1997-05-01 00:00:00,1997-06-01 00:00:00,1997-07-01 00:00:00,1997-08-01 00:00:00,1997-09-01 00:00:00,1997-10-01 00:00:00,1997-11-01 00:00:00,1997-12-01 00:00:00,1998-01-01 00:00:00,1998-02-01 00:00:00,1998-03-01 00:00:00,1998-04-01 00:00:00,1998-05-01 00:00:00,1998-06-01 00:00:00
user_id,,,,,,,,,,,,,,,,,,
1,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
2,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
3,0.722222,-0.277778,0.722222,0.722222,-0.277778,-0.277778,-0.277778,-0.277778,-0.277778,-0.277778,0.722222,-0.277778,-0.277778,-0.277778,-0.277778,-0.277778,0.722222,-0.277778
4,0.833333,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,0.833333,-0.166667,-0.166667,-0.166667,0.833333,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667
5,0.500000,0.500000,-0.500000,0.500000,0.500000,0.500000,0.500000,-0.500000,0.500000,-0.500000,-0.500000,0.500000,0.500000,-0.500000,-0.500000,-0.500000,-0.500000,-0.500000
6,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
7,0.833333,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,0.833333,-0.166667,-0.166667,-0.166667,-0.166667,0.833333,-0.166667,-0.166667,-0.166667
8,0.611111,0.611111,-0.388889,-0.388889,-0.388889,0.611111,0.611111,-0.388889,-0.388889,-0.388889,0.611111,0.611111,-0.388889,-0.388889,0.611111,-0.388889,-0.388889,-0.388889
9,0.833333,-0.166667,-0.166667,-0.166667,0.833333,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,0.833333
10,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
11,0.833333,-0.166667,0.833333,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,0.833333,-0.166667,-0.166667,-0.166667,-0.166667
12,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
13,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
14,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
15,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
16,0.833333,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,0.833333,-0.166667,0.833333,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667
17,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
18,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
19,0.888889,-0.111111,-0.111111,-0.111111,-0.111111,0.888889,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111
20,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
21,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
22,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
24,0.888889,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,0.888889,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111
25,0.611111,-0.388889,-0.388889,-0.388889,-0.388889,-0.388889,0.611111,0.611111,-0.388889,0.611111,-0.388889,-0.388889,-0.388889,-0.388889,-0.388889,0.611111,0.611111,0.611111
26,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
27,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
28,0.888889,-0.111111,0.888889,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111
29,0.500000,0.500000,0.500000,0.500000,0.500000,-0.500000,0.500000,-0.500000,0.500000,-0.500000,0.500000,-0.500000,-0.500000,-0.500000,-0.500000,0.500000,-0.500000,-0.500000
30,0.888889,0.888889,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23541,-0.111111,-0.111111,0.888889,0.888889,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111
23542,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23543,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23544,-0.166667,-0.166667,0.833333,-0.166667,0.833333,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,0.833333,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667
23545,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23546,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23547,-0.111111,-0.111111,0.888889,0.888889,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111
23548,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23549,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23550,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23551,-0.222222,-0.222222,0.777778,-0.222222,-0.222222,0.777778,-0.222222,0.777778,0.777778,-0.222222,-0.222222,-0.222222,-0.222222,-0.222222,-0.222222,-0.222222,-0.222222,-0.222222
23552,-0.111111,-0.111111,0.888889,0.888889,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111
23553,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23554,-0.111111,-0.111111,0.888889,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,0.888889,-0.111111,-0.111111,-0.111111,-0.111111
23555,-0.277778,-0.277778,0.722222,-0.277778,-0.277778,-0.277778,-0.277778,-0.277778,-0.277778,0.722222,-0.277778,0.722222,-0.277778,-0.277778,-0.277778,-0.277778,0.722222,0.722222
23556,-0.333333,-0.333333,0.666667,-0.333333,-0.333333,0.666667,0.666667,-0.333333,0.666667,-0.333333,-0.333333,-0.333333,0.666667,-0.333333,-0.333333,-0.333333,-0.333333,0.666667
23557,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23558,-0.222222,-0.222222,0.777778,-0.222222,0.777778,0.777778,-0.222222,-0.222222,-0.222222,-0.222222,-0.222222,-0.222222,-0.222222,0.777778,-0.222222,-0.222222,-0.222222,-0.222222
23559,-0.166667,-0.166667,0.833333,-0.166667,0.833333,0.833333,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667
23560,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23561,-0.166667,-0.166667,0.833333,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,0.833333,-0.166667,-0.166667,-0.166667,0.833333,-0.166667
23562,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23563,-0.111111,-0.111111,0.888889,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,0.888889,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111
23564,-0.166667,-0.166667,0.833333,-0.166667,0.833333,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,0.833333,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667,-0.166667
23565,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23566,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23567,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23568,-0.111111,-0.111111,0.888889,0.888889,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111,-0.111111
23569,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556
23570,-0.055556,-0.055556,0.944444,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556,-0.055556

In [90]:
def active_status(data):
    status=[]
    for i in range(18):
        if data[i]==0:
            if len(status)>0:
                if status[i-1]=="unreg":
                    status.append("unreg")
                else:
                    status.append("unactive")
            else:
                status.append("unreg")
        else:
            if len(status)==0:
                status.append("new")
            else:
                if status[i-1]=="unactive":
                    status.append("return")
                elif status[i-1]=="unreg":
                    status.append("new")
                else:
                    status.append("active")
    return status

In [110]:
purchase_stats=df_purchase.apply(active_status,axis=1)

In [112]:
purchase_stats.reset_index()

       user_id                                                  0
0            1  [new, unactive, unactive, unactive, unactive, ...
1            2  [new, unactive, unactive, unactive, unactive, ...
2            3  [new, unactive, return, active, unactive, unac...
3            4  [new, unactive, unactive, unactive, unactive, ...
4            5  [new, active, unactive, return, active, active...
5            6  [new, unactive, unactive, unactive, unactive, ...
6            7  [new, unactive, unactive, unactive, unactive, ...
7            8  [new, active, unactive, unactive, unactive, re...
8            9  [new, unactive, unactive, unactive, return, un...
9           10  [new, unactive, unactive, unactive, unactive, ...
10          11  [new, unactive, return, unactive, unactive, un...
11          12  [new, unactive, unactive, unactive, unactive, ...
12          13  [new, unactive, unactive, unactive, unactive, ...
13          14  [new, unactive, unactive, unactive, unactive, ...
14          15  [new, unactive, unactive, unactive, unactive, ...
15          16  [new, unactive, unactive, unactive, unactive, ...
16          17  [new, unactive, unactive, unactive, unactive, ...
17          18  [new, unactive, unactive, unactive, unactive, ...
18          19  [new, unactive, unactive, unactive, unactive, ...
19          20  [new, unactive, unactive, unactive, unactive, ...
20          21  [new, unactive, unactive, unactive, unactive, ...
21          22  [new, unactive, unactive, unactive, unactive, ...
22          23  [new, unactive, unactive, unactive, unactive, ...
23          24  [new, unactive, unactive, unactive, unactive, ...
24          25  [new, unactive, unactive, unactive, unactive, ...
25          26  [new, unactive, unactive, unactive, unactive, ...
26          27  [new, unactive, unactive, unactive, unactive, ...
27          28  [new, unactive, return, unactive, unactive, un...
28          29  [new, active, active, active, active, unactive...
29          30  [new, active, unactive, unactive, unactive, un...
...        ...                                                ...
23540    23541  [unreg, unreg, new, active, unactive, unactive...
23541    23542  [unreg, unreg, new, unactive, unactive, unacti...
23542    23543  [unreg, unreg, new, unactive, unactive, unacti...
23543    23544  [unreg, unreg, new, unactive, return, unactive...
23544    23545  [unreg, unreg, new, unactive, unactive, unacti...
23545    23546  [unreg, unreg, new, unactive, unactive, unacti...
23546    23547  [unreg, unreg, new, active, unactive, unactive...
23547    23548  [unreg, unreg, new, unactive, unactive, unacti...
23548    23549  [unreg, unreg, new, unactive, unactive, unacti...
23549    23550  [unreg, unreg, new, unactive, unactive, unacti...
23550    23551  [unreg, unreg, new, unactive, unactive, return...
23551    23552  [unreg, unreg, new, active, unactive, unactive...
23552    23553  [unreg, unreg, new, unactive, unactive, unacti...
23553    23554  [unreg, unreg, new, unactive, unactive, unacti...
23554    23555  [unreg, unreg, new, unactive, unactive, unacti...
23555    23556  [unreg, unreg, new, unactive, unactive, return...
23556    23557  [unreg, unreg, new, unactive, unactive, unacti...
23557    23558  [unreg, unreg, new, unactive, return, active, ...
23558    23559  [unreg, unreg, new, unactive, return, active, ...
23559    23560  [unreg, unreg, new, unactive, unactive, unacti...
23560    23561  [unreg, unreg, new, unactive, unactive, unacti...
23561    23562  [unreg, unreg, new, unactive, unactive, unacti...
23562    23563  [unreg, unreg, new, unactive, unactive, unacti...
23563    23564  [unreg, unreg, new, unactive, return, unactive...
23564    23565  [unreg, unreg, new, unactive, unactive, unacti...
23565    23566  [unreg, unreg, new, unactive, unactive, unacti...
23566    23567  [unreg, unreg, new, unactive, unactive, unacti...
23567    23568  [unreg, unreg, new, active, unactive, unactive...
23568    23569  [unreg, unreg, new, unactive, unactive, unacti...
23569    23570  [unreg, unreg, new, unactive, unactive, unacti...

[23570 rows x 2 columns]

In [59]:
purchase_stats.columns=list(pivoted_counts.columns)

In [99]:
purchase_stats.head()

user_id
1    [new, unactive, unactive, unactive, unactive, ...
2    [new, unactive, unactive, unactive, unactive, ...
3    [new, unactive, return, active, unactive, unac...
4    [new, unactive, unactive, unactive, unactive, ...
5    [new, active, unactive, return, active, active...
dtype: object

In [46]:
df_purchase.columns

DatetimeIndex(['1997-01-01', '1997-02-01', '1997-03-01', '1997-04-01',
               '1997-05-01', '1997-06-01', '1997-07-01', '1997-08-01',
               '1997-09-01', '1997-10-01', '1997-11-01', '1997-12-01',
               '1998-01-01', '1998-02-01', '1998-03-01', '1998-04-01',
               '1998-05-01', '1998-06-01'],
              dtype='datetime64[ns]', name='month', freq=None)

In [100]:
purchase_stats.columns==df_purchase.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [109]:
order_diff=df.groupby("user_id").apply(lambda x:x.order_dt-x.order_dt.shift())

user_id
1        0            NaT
2        1            NaT
         2         0 days
3        3            NaT
         4        87 days
         5         3 days
         6       227 days
         7        10 days
         8       184 days
4        9            NaT
         10       17 days
         11      196 days
         12      132 days
5        13           NaT
         14       13 days
         15       21 days
         16       66 days
         17       50 days
         18       16 days
         19       36 days
         20       55 days
         21       84 days
         22        4 days
         23       22 days
6        24           NaT
7        25           NaT
         26      283 days
         27      162 days
8        28           NaT
         29       43 days
                   ...
23556    69629    63 days
         69630    98 days
         69631   155 days
23557    69632        NaT
23558    69633        NaT
         69634    54 days
         69635    37 days
         69636   246 days
23559    69637        NaT
         69638    54 days
         69639    40 days
23560    69640        NaT
23561    69641        NaT
         69642   309 days
         69643   121 days
23562    69644        NaT
23563    69645        NaT
         69646   193 days
23564    69647        NaT
         69648    57 days
         69649   193 days
23565    69650        NaT
23566    69651        NaT
23567    69652        NaT
23568    69653        NaT
         69654    11 days
         69655    17 days
23569    69656        NaT
23570    69657        NaT
         69658     1 days
Name: order_dt, Length: 69659, dtype: timedelta64[ns]